# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test-job-8:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test
  test-job-10:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test

  publish-job:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
          name: Pre-Publish Script
          command: ./tools/publish.sh
      - run: npm run build
      - run: npm run publish

workflows:
  version: 2
  test:
    jobs:
      - test-job-8
      - test-job-10
      - publish-job:
          filters:
            branches:
              only:
                - master
          requires:
            - test-job-8
            - test-job-10
