# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test-job-8:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm run build
      - run: npm test
      - save_cache:
          paths:
            - node_modules
            - packages/cli
          key: v1-dependencies-{{ checksum "package-lock.json" }}
  test-job-10:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm run build
      - run: npm test
      - save_cache:
          paths:
            - node_modules
            - packages/cli
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  publish-job:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Pre-Publish Script
          command: ./tools/publish.sh
      - run: npm run build
      - run: npm run publish

workflows:
  version: 2
  test:
    jobs:
      - test-job-8
      - test-job-10
      - publish-job:
          filters:
            branches:
              only:
                - master
          requires:
            - test-job-8
            - test-job-10
